opt_in_rules:
  - array_init
  - closure_end_indentation
  - contains_over_first_not_nil
  - empty_count: yes
  - explicit_enum_raw_value
  - explicit_top_level_acl: warning
  - explicit_type_interface
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - nimble_operator
  - no_grouping_extension
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - redundant_type_annotation
  - yoda_condition

excluded:
  - Carthage
  - Fabric/Common/AppDelegate.swift

nesting:
  type_level: 2
line_length:
  - 180
function_body_length:
  - 40 # Warning
  - 100 # Error
type_body_length:
  - 200 # Warning
  - 300 # Error
